# Generated by Django 3.0 on 2020-03-31 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='inv_locat',
            new_name='inv_location',
        ),
    ]
