# Generated by Django 3.0 on 2020-04-04 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventapp', '0006_auto_20200404_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='inv_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='pay_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='inv_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
