# Generated by Django 3.0 on 2020-04-04 16:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventapp', '0007_auto_20200404_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.PositiveIntegerField()),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_mobile', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Please Enter A Valid Mobile Number!', regex='^(?:(?:\\+|0{0,2})91(\\s*[\\ -]\\s*)?|[0]?)?[6789]\\d{9}|(\\d[ -]?){10}\\d$')])),
                ('customer_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_id', models.PositiveIntegerField()),
                ('inv_name', models.CharField(max_length=100)),
                ('inv_location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.PositiveIntegerField()),
                ('item_stock', models.PositiveIntegerField()),
                ('item_minimum_required', models.PositiveIntegerField()),
                ('item_name', models.CharField(max_length=100)),
                ('inv_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_item', to='inventapp.Inventory')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_id', models.PositiveIntegerField()),
                ('user_mobile', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Please Enter A Valid Mobile Number!', regex='^(?:(?:\\+|0{0,2})91(\\s*[\\ -]\\s*)?|[0]?)?[6789]\\d{9}|(\\d[ -]?){10}\\d$')])),
                ('inv_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_user', to='inventapp.Inventory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_id', models.PositiveIntegerField()),
                ('pay_date', models.DateField()),
                ('pay_amount', models.PositiveIntegerField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_payment', to='inventapp.Customer')),
                ('users_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payment', to='inventapp.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to='inventapp.Customer')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_orders', to='inventapp.Item')),
                ('pay_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to='inventapp.Payment')),
                ('users_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to='inventapp.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='users_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_customer', to='inventapp.UserProfile'),
        ),
    ]
