# Generated by Django 3.0 on 2020-04-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventapp', '0008_auto_20200404_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='users_id',
            field=models.CharField(max_length=20),
        ),
    ]
