# Generated by Django 3.0 on 2020-04-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventapp', '0009_auto_20200404_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='users_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='users',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
