# Generated by Django 3.0 on 2020-04-04 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventapp', '0011_auto_20200404_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='inv_id',
            new_name='inv',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='pay_id',
            new_name='pay',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
